package com.bryan4.dao;

import com.bryan4.pojo.Emp;
import com.bryan4.pojo.EmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@SuppressWarnings("all")
public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Apr 21 20:57:01 CST 2023
     */
    long countByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Apr 21 20:57:01 CST 2023
     */
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Apr 21 20:57:01 CST 2023
     */
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Apr 21 20:57:01 CST 2023
     */
    int insert(Emp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Apr 21 20:57:01 CST 2023
     */
    int insertSelective(Emp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Apr 21 20:57:01 CST 2023
     */
    List<Emp> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Apr 21 20:57:01 CST 2023
     */
    Emp selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Apr 21 20:57:01 CST 2023
     */
    int updateByExampleSelective(@Param("row") Emp row, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Apr 21 20:57:01 CST 2023
     */
    int updateByExample(@Param("row") Emp row, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * 有选择性的更新数据，例如 emp(eid=1, empName='李四', age=27, job=null)
     * 则为null的属性值不参与更新
     *
     * @mbg.generated Fri Apr 21 20:57:01 CST 2023
     */
    int updateByPrimaryKeySelective(Emp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * 不做选择性更新数据，例如 emp(eid=1, empName='李四', age=27, job=null)
     * 则为null的属性值也要参与更新
     *
     * @mbg.generated Fri Apr 21 20:57:01 CST 2023
     */
    int updateByPrimaryKey(Emp row);
}